version: '3.3'
 
services:
  mongodb:
    build:
      context:  ./mongodb
      dockerfile: Dockerfile
    expose:
      - "27017"
    ports:
      - "27017:27017"
    environment:
      - "xpack.security.enabled:false"

  elasticsearch:
    build:
      context:  ./elasticsearch
      dockerfile: Dockerfile
    expose:
      - "9200"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - http.host=0.0.0.0
      - xpack.security.enabled=false

  beats:
    build:
      context:  ./metric-beats
      dockerfile: Dockerfile
    links:
      - mongodb:mongo
      - elasticsearch:elastic
    depends_on:
      - mongodb
      - elasticsearch